//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        public int kamarID { get; set; }
        public Nullable<int> Harga { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public string Jenis { get; set; }
    }
}
