//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessDomainObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penerbangan
    {
        public int PenerbanganID { get; set; }
        public string Pesawat { get; set; }
        public Nullable<int> JlhKursi { get; set; }
        public Nullable<int> Harga { get; set; }
        public string Asal { get; set; }
        public string Tujuan { get; set; }
        public Nullable<System.DateTime> Terbang { get; set; }
    }
}
